apiVersion: "v1"
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: containerize-step-by-step
spec:
  ports:
    - port: 6379
      name: redis-tcp
      targetPort: 6379
  # selector pointing to redis-healthcheck-pod.yml metadata.labels
  selector:
    name: redis
    app: containerize-step-by-step
