apiVersion: "v1"
kind: Pod
metadata:
  name: redis-healthcheck
  labels:
    name: redis-healthcheck
    app: containerize-step-by-step
spec:
  containers:
    - name: redis-healthcheck
      image: healthcheck/redis:alpine
      ports:
        - containerPort: 6379
          protocol: TCP
