apiVersion: "v1"
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    app: containerize-step-by-step
spec:
  containers:
    - name: redis
      image: healthcheck/redis:alpine
      ports:
        - containerPort: 6379
          protocol: TCP
          name: redis
