apiVersion: "v1"
kind: Pod
metadata:
  name: commander
  labels:
    name: commander
    app: containerize-step-by-step
spec:
  containers:
    - name: commander
      image: localhost:5000/redis-commander-healthcheck:latest
#      image: localhost:5000/redis-commander-healthcheck:1
      ports:
        - containerPort: 8081
          name: commander
          protocol: TCP
