apiVersion: "v1"
kind: Service
metadata:
  name: commander
  labels:
    name: commander
    app: containerize-step-by-step
spec:
  ports:
    - port: 8081
      name: commander-http
      targetPort: 8081
  # expose port `minikube service web-app --url`
  type: NodePort
  # selector pointing to pod metadata.labels
  selector:
    name: commander
    app: containerize-step-by-step
