apiVersion: "v1"
kind: Service
metadata:
  name: web-app
  labels:
    name: web-app
    app: containerize-step-by-step
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: web-app-http
  type: NodePort # expose port `minikube service web-app --url`
  # selector pointing to web-app-healthcheck-pod.yml metadata.labels
  selector:
    name: web-app
    app: containerize-step-by-step
