apiVersion: "v1"
kind: Service
metadata:
  name: web-app-healthcheck
  labels:
    name: web-app-healthcheck
    app: containerize-step-by-step
spec:
  ports:
    - port: 8080
      name: web-app-healthcheck
      targetPort: 8080
  # selector pointing to web-app-healthcheck-pod.yml metadata.labels
  selector:
    name: web-app-healthcheck
    app: containerize-step-by-step
