apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: color-app
spec:
  containers:
    - name: color-app
      image: 127.0.0.1:5000/app:latest
      env:
        - name: COLOR
          value: green

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: color-app
    spec:
      containers:
        - name: color-app
          image: 127.0.0.1:5000/app:latest
          env:
            - name: COLOR
              value: green

---

apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: color-app
