FROM tenstartups/redis-commander
MAINTAINER Maksim Kostromin https://github.comm/daggerok
RUN apk --no-cache add curl
HEALTHCHECK --interval=15s --timeout=15s --retries=15 CMD curl -f http://127.0.0.1:8081 || exit 1
